# Generated by Django 4.2.4 on 2023-09-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_vehicles_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicles", name="image",),
    ]
