# Generated by Django 4.2.4 on 2023-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0004_remove_vehicles_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicles",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
